version: '3.4'

services:
  db:  
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "BigPassw0rd"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '1433:1433'  
    expose:  
      - 1433
  magomesbank.presentation.api:
    image: ${DOCKER_REGISTRY-}magomesbankpresentationapi
    build:
      context: .
      dockerfile: MagomesBank.Presentation.API/Dockerfile
  magomesbank.presentation.web:
    image: ${DOCKER_REGISTRY-}magomesbankpresentationweb
    build:
      context: .
      dockerfile: Dockerfile    
  magomesbank.angular.app:
    image: ${DOCKER_REGISTRY-}magomesbankangularapp
    build:
      context: .
      dockerfile: DockerfileApp
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./MagomesBank.Presentation.Web/ClientApp:/app